---
apiVersion: v1
kind: Template
metadata:
  name: assisted-installer-ui-chatbot
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: assisted-installer-ui-chatbot
    spec:
      feoConfigEnabled: true
      envName: ${ENV_NAME}
      title: Assisted Installer UI Chatbot
      deploymentRepo: https://github.com/openshift-assisted/assisted-installer-ui
      frontend:
        paths:
          - /apps/assisted-installer-ui-chatbot
      API:
        versions:
          - v1
      image: ${IMAGE}:${IMAGE_TAG}
      module:
        manifestLocation: '/apps/assisted-installer-ui-chatbot/fed-mods.json'
        moduleConfig:
          ssoScopes:
            - rhfull
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/app-sre/assisted-installer-ui-chatbot
